Repository sai-lab/sai-lab.github.io, pull requests merged in 2022-05, with the labels that each got.

#14 add: link check actions in markdown
  .github/settings/markdown-link-check.json
  .github/workflows/linkcheck.yml
  mdfiles/index.md
  mdfiles/wiki/assign.md
  mdfiles/wiki/thesis.md
  mdfiles/workshop/okayama.md
Labels: bug, pls Merge

#13 Change link path
  .github/workflows/build-to-html.yml
  .github/workflows/release-html.yml
  docs/images/.gitkeep
  docs/images/desk2.jpeg
  docs/images/logo.png
  docs/images/map10f.png
  docs/images/members2021.jpeg
  docs/images/rack2.jpeg
  docs/images/theme/distributed-web-system.png
  docs/images/theme/introduction.png
  docs/images/theme/priority-access-system.png
  docs/images/theme/protec-kun_01.png
  docs/images/theme/protec-kun_02.png
  docs/images/theme/protec-kun_03.png
  docs/images/theme/protec-kun_04.png
  docs/images/theme/runu-system-arch.png
  docs/images/theme/security_system.png
  docs/images/theme/target.png
  docs/images/theme/vda-ui.png
  docs/images/theme/zeroday_attack.png
  docs/public_material/Intro_Saisho-Lab.pdf
  docs/public_material/s20g451_introduction.pdf
  docs/public_material/s20g470-AERG2020.pdf
  docs/public_material/s20g470-IntroResearch.pdf
  docs/public_material/s20g477-IntroResearch.pdf
  docs/templates/style.css
  docs/templates/template.html
  images
  main.js
  mdfiles/images
  mdfiles/index.md
  mdfiles/public_material
  mdfiles/static/index.md
  mdfiles/templates
  mdfiles/wiki/theme.md
  public_material
  templates
Labels: pls Merge

#18 add: uses gh-deploy
  .github/workflows/release-html.yml
Labels: bug

#23 add: dot path
  main.js
Labels: bug

#17 CSSの適応
  docs/templates/style.css
  docs/templates/template.html
  main.js
  mdfiles/index.md
  mdfiles/wiki/assign.md
  mdfiles/wiki/member.md
  mdfiles/wiki/result.md
  mdfiles/wiki/theme.md
  mdfiles/wiki/thesis.md
  mdfiles/workshop/okayama.md
Labels: bug, pls Merge

#24 add: favicon
  docs/images/favicon.ico
  docs/templates/template.html
Labels: pls Merge
